version: '3.8'

services:
  zookeeper:
    logging:
      driver: "none" 
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [paypal-network]
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s 
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    logging:
      driver: "none" 
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    container_name: kafka
    depends_on:
      zookeeper: { condition: service_healthy } 
    networks: [paypal-network]  
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      
  kafka-init:   
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka: { condition: service_healthy }
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic txn-initiated --partitions 1 --replication-factor 1 && echo 'Topic created'"
    networks: [paypal-network]


# ─── Databases ───────────────────────────────────────────
  postgres-user:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: user-db
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks: [paypal-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d user-db"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 10s

  postgres-wallet:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: wallet123
      POSTGRES_DB: wallet-db
    volumes:
      - postgres_wallet_data:/var/lib/postgresql/data
    networks: [paypal-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d wallet-db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres-txn:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: txn
      POSTGRES_PASSWORD: txn123
      POSTGRES_DB: txn-db
    volumes:
      - postgres_txn_data:/var/lib/postgresql/data
    networks: [paypal-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U txn -d txn-db"]
      interval: 5s
      retries: 5

  postgres-reward:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: reward123
      POSTGRES_DB: reward-db
    volumes:
      - postgres_reward_data:/var/lib/postgresql/data
    networks: [paypal-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d reward-db"]
      interval: 5s
      retries: 5

  postgres-notify:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: notify123
      POSTGRES_DB: notify-db
    volumes:
      - postgres_notify_data:/var/lib/postgresql/data
    networks: [paypal-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d notify-db"]
      interval: 5s
      retries: 5

  # ─── Microservices ───────────────────────────────────────
  user-service:
    build: ./user-service
    env_file: ./user-service/.env
    depends_on:
      postgres-user: { condition: service_healthy }
    networks: [paypal-network]

  wallet-service:
    build: ./wallet-service
    env_file: ./wallet-service/.env
    depends_on:
      postgres-wallet: { condition: service_healthy }
    networks: [paypal-network]

  transaction-service:
    build: ./transaction-service
    env_file: ./transaction-service/.env
    depends_on:
      postgres-txn: { condition: service_healthy }
      kafka: { condition: service_healthy }
      wallet-service: { condition: service_started }
    networks: [paypal-network]

  notification-service:
    build: ./notification-service
    env_file: ./notification-service/.env
    depends_on:
      postgres-notify: { condition: service_healthy }
      kafka-init: { condition: service_completed_successfully }
    networks: [paypal-network]

  reward-service:
    build: ./reward-service
    env_file: ./reward-service/.env
    depends_on:
      postgres-reward: { condition: service_healthy }
      kafka-init: { condition: service_completed_successfully }
    networks: [paypal-network]

  api-gateway:
    build: ./api-gateway
    env_file: ./api-gateway/.env
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - wallet-service
      - transaction-service
      - notification-service
      - reward-service
    networks: [paypal-network]

networks:
  paypal-network:
    driver: bridge


volumes:
  postgres_user_data:
  postgres_wallet_data:
  postgres_txn_data:
  postgres_reward_data:
  postgres_notify_data:
